# 1. Power Analysis

## Objective

Previous notebooks established whether the observed differences in player retention were statistically significant.

This notebook evaluates the quality of the experiment itself by answering the following questions:

- Did the experiment include enough players?
- Was the sample size sufficient to detect the observed effects?
- Could a meaningful difference have gone unnoticed?
- How should similar experiments be designed in the future?

Power analysis complements hypothesis testing by assessing the ability of an experiment to detect true treatment effects.

# 2. Why Power Analysis Matters

## Statistical significance is only part of the story.

A statistically significant result does not necessarily imply that the experiment was well designed.

Power analysis helps determine whether the experiment had a high probability of detecting a true effect if one actually existed.

Without adequate statistical power:

- Real improvements may go undetected.
- Business decisions may be based on inconclusive evidence.
- Additional experimentation may be required.

# 3. Statistical Power

## 3.1 Objective

Estimate the statistical power of the Cookie Cats experiment using the observed effect size and sample sizes.

Statistical power represents the probability of correctly detecting a true difference between the experiment groups when one actually exists.

## 3.2 Theory

Statistical power is the probability of rejecting the null hypothesis when a true treatment effect exists.

Power depends on four key factors:

- Sample size
- Effect size
- Significance level (α)
- Data variability

A commonly accepted benchmark is **80% power**, meaning the experiment has an 80% chance of detecting a meaningful effect if it truly exists.

Higher statistical power reduces the likelihood of false negatives and improves confidence in experimental conclusions.

## 3.3 Compute Statistical Power

Estimate the statistical power using the observed effect size from the seven-day retention analysis and the sample sizes of both experiment groups.

The calculation assumes a two-sided hypothesis test with a significance level of 5%.

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from scipy.stats import chisquare

In [2]:
df = pd.read_csv("../data/cleaned/cookie_cats_cleaned.csv")

In [1]:
from statsmodels.stats.power import NormalIndPower

analysis = NormalIndPower()

# Observed Cohen's h from Notebook 03
effect_size = 0.0211

# Smaller group size
nobs = min(44700, 45489)

alpha = 0.05

power = analysis.solve_power(
    effect_size=effect_size,
    nobs1=nobs,
    alpha=alpha,
    ratio=1,
    alternative="two-sided"
)

print(f"Observed Effect Size : {effect_size:.4f}")
print(f"Sample Size          : {nobs}")
print(f"Significance Level   : {alpha}")
print(f"Statistical Power    : {power:.4f}")

Observed Effect Size : 0.0211
Sample Size          : 44700
Significance Level   : 0.05
Statistical Power    : 0.8839


## 3.4 Interpretation

### Results

- **Observed Effect Size (Cohen's h):** 0.0211
- **Sample Size:** 44,700 players per group (minimum group size)
- **Statistical Power:** 88.39%

### Key Insights

- The experiment achieved **88.39% statistical power**, exceeding the commonly accepted benchmark of 80%.
- The available sample size was sufficient to detect the observed retention difference with high probability.
- The likelihood of failing to detect a true effect (Type II Error) was relatively low.

### Business Perspective

The Cookie Cats experiment was adequately powered, indicating that the observed seven-day retention improvement is unlikely to be the result of an insufficient sample size. This increases confidence in the reliability of the experimental findings.

# 4. Minimum Detectable Effect (MDE)

## 4.1 Objective

Estimate the smallest retention improvement that this experiment could reliably detect given its sample size, significance level, and desired statistical power.

## 4.2 Theory

The **Minimum Detectable Effect (MDE)** is the smallest effect size that an experiment can detect with a specified level of confidence and statistical power.

MDE depends on:

- Sample size
- Statistical power
- Significance level (α)

Experiments with larger sample sizes can reliably detect smaller effects, while smaller experiments require larger differences before statistical significance can be achieved.

MDE is commonly used when planning A/B tests to determine the required sample size before launching an experiment.

## 4.3 Compute the Minimum Detectable Effect

Estimate the minimum standardized effect size that this experiment could detect while maintaining 80% statistical power at a 5% significance level.

In [2]:
desired_power = 0.80

mde = analysis.solve_power(
    power=desired_power,
    nobs1=nobs,
    alpha=alpha,
    ratio=1,
    alternative="two-sided"
)

print(f"Desired Statistical Power : {desired_power:.2f}")
print(f"Minimum Detectable Effect (Cohen's h): {mde:.4f}")

Desired Statistical Power : 0.80
Minimum Detectable Effect (Cohen's h): 0.0187


## 4.4 Interpretation

### Results

- **Desired Statistical Power:** 80%
- **Minimum Detectable Effect (Cohen's h):** 0.0187

### Key Insights

- The experiment could reliably detect standardized effects of **0.0187 or larger**.
- The observed effect size (**0.0211**) exceeded the minimum detectable effect.
- This indicates that the experiment had sufficient sensitivity to identify the observed difference in seven-day retention.

### Business Perspective

The experiment was capable of detecting very small changes in player retention. Since the observed effect exceeded the minimum detectable threshold, the statistical significance observed in the seven-day analysis is supported by an appropriately sensitive experimental design.

# 5. Sample Size Analysis

## 5.1 Objective

Estimate the minimum number of players required in each experiment group to detect the observed effect size with 80% statistical power at a 5% significance level.

## 5.2 Compute Required Sample Size

Estimate the required sample size per experiment group using the observed effect size from the seven-day retention analysis.

In [3]:
required_sample = analysis.solve_power(
    effect_size=effect_size,
    power=0.80,
    alpha=0.05,
    ratio=1,
    alternative="two-sided"
)

print(f"Required Sample Size per Group : {required_sample:.0f}")
print(f"Actual Sample Size per Group   : {nobs}")

Required Sample Size per Group : 35259
Actual Sample Size per Group   : 44700


## 5.3 Interpretation

### Results

- **Required Sample Size per Group:** 35,259 players
- **Actual Sample Size per Group:** 44,700 players

### Key Insights

- The actual sample size exceeded the required sample size by approximately **9,441 players per group**.
- The experiment included enough participants to detect the observed effect with the desired statistical power.
- The available sample size increased the reliability and precision of the statistical estimates.

### Business Perspective

The Cookie Cats experiment was designed with a sufficiently large sample size to detect small but meaningful changes in player retention. This supports the credibility of the experimental conclusions and suggests that future experiments targeting similar effect sizes should aim for a comparable sample size.

# 6. Was Our Experiment Well Powered?

## 6.1 Experiment Evaluation

The following table summarizes the key power analysis metrics used to evaluate the quality of the experimental design.

In [7]:
power_summary = pd.DataFrame({
    "Metric": [
        "Observed Effect Size (Cohen's h)",
        "Minimum Detectable Effect (MDE)",
        "Desired Statistical Power",
        "Observed Statistical Power",
        "Required Sample Size",
        "Actual Sample Size",
        "Experiment Status"
    ],
    "Value": [
        "0.0211",
        "0.0187",
        "80%",
        "88.39%",
        "35,259",
        "44,700",
        "Well Powered"
    ]
})

power_summary

,Metric,Value
0,Observed Effect Size (Cohen's h),0.0211
1,Minimum Detectable Effect (MDE),0.0187
2,Desired Statistical Power,80%
3,Observed Statistical Power,88.39%
4,Required Sample Size,"35,259"
5,Actual Sample Size,"44,700"
6,Experiment Status,Well Powered


## 6.2 Interpretation

### Key Findings

- The experiment achieved **88.39% statistical power**, exceeding the commonly accepted target of 80%.
- The observed effect size (**0.0211**) was larger than the minimum detectable effect (**0.0187**).
- The actual sample size exceeded the required sample size needed to achieve the desired statistical power.
- Together, these findings indicate that the experiment was adequately powered to detect the observed difference in seven-day retention.

### Business Perspective

The statistical power analysis indicates that the Cookie Cats experiment was well designed from a sampling perspective. The available sample size provided sufficient sensitivity to detect small improvements in player retention, increasing confidence that the experimental conclusions are reliable.

# 7. Business Recommendations

## Recommendations

Based on the statistical power analysis, the following recommendations can be made:

- Continue using sufficiently large sample sizes when evaluating product changes.
- Define the minimum detectable effect before launching future A/B tests to ensure meaningful improvements can be identified.
- Consider both statistical significance and practical significance when making product decisions.
- Complement retention analysis with additional business metrics such as monetization, session duration, player progression, and user satisfaction.

# 8. Key Takeaways

## Summary

- The experiment achieved **88.39% statistical power**, exceeding the recommended threshold of 80%.
- The observed effect size was larger than the minimum detectable effect, indicating that the experiment was capable of identifying the observed retention difference.
- The actual sample size exceeded the estimated requirement, supporting the reliability of the statistical conclusions.
- Overall, the Cookie Cats A/B test was well powered and appropriately designed to evaluate the impact of moving the progression gate from Level 30 to Level 40.

## Final Conclusion

From an experimental design perspective, the Cookie Cats A/B test provides reliable evidence that the observed difference in seven-day retention is supported by an adequately powered study. The conclusions drawn from previous notebooks are therefore strengthened by this analysis.